# Generated by Django 2.0 on 2020-10-08 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_image_date_of_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='photo_upload',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
