# Generated by Django 3.1.2 on 2020-10-09 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0005_auto_20201009_2314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='photo_upload',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='image',
            name='image_name',
        ),
    ]
