# Generated by Django 3.1.2 on 2020-10-10 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0006_auto_20201010_0013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='category',
        ),
        migrations.AddField(
            model_name='image',
            name='categories',
            field=models.ManyToManyField(related_name='photos', to='photo.Category'),
        ),
    ]
