# Generated by Django 3.1.2 on 2020-10-10 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0007_auto_20201010_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='season',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
