# Generated by Django 3.1.2 on 2020-10-12 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0012_auto_20201012_0713'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['cat'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['created'], 'verbose_name': 'Image', 'verbose_name_plural': 'Images'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['geo_tag'], 'verbose_name': 'Location', 'verbose_name_plural': 'Locations'},
        ),
        migrations.AlterField(
            model_name='category',
            name='cat',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='geo_tag',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
