# Generated by Django 3.1.2 on 2020-10-12 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0013_auto_20201012_1347'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['cat_type'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='cat',
        ),
        migrations.AddField(
            model_name='category',
            name='cat_type',
            field=models.CharField(choices=[('sports', 'Sports'), ('family', 'Family'), ('travel', 'Travel'), ('technology', 'Technology')], default='family', max_length=20),
        ),
    ]
