# Generated by Django 3.1.2 on 2020-10-12 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0014_auto_20201012_1442'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['cat'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='cat_type',
        ),
        migrations.AddField(
            model_name='category',
            name='cat',
            field=models.CharField(default='travel', max_length=30, unique=True),
        ),
    ]
