# Generated by Django 3.1.2 on 2020-10-12 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0015_auto_20201012_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat',
            field=models.CharField(default='unknown', max_length=30, unique=True),
        ),
    ]
