# Generated by Django 3.1.2 on 2020-10-12 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0016_auto_20201012_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
