# Generated by Django 3.1.2 on 2020-10-13 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0017_auto_20201013_0123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='id',
        ),
        migrations.AddField(
            model_name='image',
            name='image_id',
            field=models.IntegerField(auto_created=True, default=1, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(default='photo_name', max_length=1002),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(null=True, upload_to='static/'),
        ),
    ]
