# Generated by Django 3.1.2 on 2020-10-13 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0017_auto_20201013_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(default='photo_name', max_length=1002),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(null=True, upload_to='static/'),
        ),
    ]
