# Generated by Django 3.1.2 on 2020-10-13 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [

        ('photo', '0015_auto_20201013_1318'),
        ('photo', '0018_auto_20201013_1311'),
        ('photo', '0017_auto_20201013_1316'),
    ]

    operations = [
    ]
