# Generated by Django 3.1.2 on 2020-10-13 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0021_merge_20201013_1358'),
        ('photo', '0018_auto_20201013_1158'),
    ]

    operations = [
    ]
